language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  chrome: stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- polylint
script:
- xvfb-run wct